# Generated by Django 4.2 on 2023-04-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 2')),
                ('photo_3', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 3')),
                ('photo_4', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 4')),
                ('photo_5', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 5')),
                ('photo_6', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 6')),
                ('photo_7', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 7')),
                ('photo_8', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 8')),
                ('photo_9', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 9')),
                ('photo_10', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 10')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобиля',
            },
        ),
        migrations.CreateModel(
            name='VillaPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 2')),
                ('photo_3', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 3')),
                ('photo_4', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 4')),
                ('photo_5', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 5')),
                ('photo_6', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 6')),
                ('photo_7', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 7')),
                ('photo_8', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 8')),
                ('photo_9', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 9')),
                ('photo_10', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 10')),
            ],
            options={
                'verbose_name': 'Фотография виллы',
                'verbose_name_plural': 'Фотографии виллы',
            },
        ),
        migrations.CreateModel(
            name='YachtPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 2')),
                ('photo_3', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 3')),
                ('photo_4', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 4')),
                ('photo_5', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 5')),
                ('photo_6', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 6')),
                ('photo_7', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 7')),
                ('photo_8', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 8')),
                ('photo_9', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 9')),
                ('photo_10', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото 10')),
            ],
            options={
                'verbose_name': 'Фотография яхты',
                'verbose_name_plural': 'Фотографии яхты',
            },
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Яхта', max_length=120, verbose_name='Наименование')),
                ('length', models.FloatField(verbose_name='Длина, м')),
                ('width', models.FloatField(verbose_name='Ширина, м')),
                ('cabins_number', models.IntegerField(verbose_name='Количество кают')),
                ('beds_number', models.IntegerField(verbose_name='Количество спальных мест')),
                ('maximum_speed', models.FloatField(verbose_name='Максимальная скорость, узл')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительные характеристики')),
                ('price_per_day', models.FloatField(verbose_name='Стоимость аренды на 1 сутки, евро')),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('publication_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('update_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
                ('exist', models.BooleanField(default=True, null=True, verbose_name='Предлагается?')),
                ('yacht_photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.yachtphotos', verbose_name='Фотография яхты')),
            ],
            options={
                'verbose_name': 'Яхта',
                'verbose_name_plural': 'Яхты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Вилла', max_length=120, verbose_name='Наименование')),
                ('region', models.CharField(default='Регион', max_length=50, verbose_name='Регион')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rooms_number', models.IntegerField(verbose_name='Количество комнат')),
                ('bedrooms_number', models.IntegerField(verbose_name='Количество спален')),
                ('bathrooms_number', models.IntegerField(verbose_name='Количество ванных комнат')),
                ('total_area', models.FloatField(verbose_name='Общая площадь, кв. м')),
                ('living_area', models.FloatField(verbose_name='Жилая площадь, кв. м')),
                ('sea_distance', models.CharField(max_length=10, verbose_name='Расстояние до моря')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительные характеристики')),
                ('price_per_day', models.FloatField(verbose_name='Стоимость аренды на 1 сутки, евро')),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('publication_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('update_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
                ('exist', models.BooleanField(default=True, null=True, verbose_name='Предлагается?')),
                ('villa_photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.villaphotos', verbose_name='Фотография виллы')),
            ],
            options={
                'verbose_name': 'Вилла',
                'verbose_name_plural': 'Виллы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Автомобиль', max_length=120, verbose_name='Модель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('seats_number', models.IntegerField(verbose_name='Количество мест')),
                ('doors_number', models.IntegerField(verbose_name='Количество дверей')),
                ('horsepower', models.IntegerField(verbose_name='Мощность, л.с.')),
                ('engine', models.FloatField(verbose_name='Объекм двигателя, куб. см')),
                ('transmission', models.CharField(max_length=15, verbose_name='Трансмиссия')),
                ('drive', models.CharField(max_length=15, verbose_name='Привод')),
                ('maximum_speed', models.FloatField(verbose_name='Максимальная скорость, км/час')),
                ('price_per_day', models.FloatField(verbose_name='Стоимость аренды на 1 сутки, евро')),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('publication_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('update_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
                ('exist', models.BooleanField(default=True, null=True, verbose_name='Предлагается?')),
                ('vehicle_photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.vehiclephotos', verbose_name='Фотография автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['title'],
            },
        ),
    ]
