# Generated by Django 4.2 on 2023-04-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_alter_villaphotos_photo_1_alter_villaphotos_photo_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_10',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 10'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 7'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 8'),
        ),
        migrations.AlterField(
            model_name='vehiclephotos',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 9'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_10',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 10'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 7'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 8'),
        ),
        migrations.AlterField(
            model_name='villaphotos',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 9'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_10',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 10'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 7'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 8'),
        ),
        migrations.AlterField(
            model_name='yachtphotos',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 9'),
        ),
    ]
