# Generated by Django 4.2 on 2023-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_alter_vehiclephotos_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Цвет кузова'),
        ),
    ]
