# Generated by Django 4.2 on 2023-04-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0005_alter_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_photos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.vehiclephotos', verbose_name='Фотография автомобиля'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bathrooms_number',
            field=models.IntegerField(null=True, verbose_name='Количество ванных комнат'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bedrooms_number',
            field=models.IntegerField(null=True, verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='living_area',
            field=models.FloatField(null=True, verbose_name='Жилая площадь, кв. м'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='rooms_number',
            field=models.IntegerField(null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='total_area',
            field=models.FloatField(null=True, verbose_name='Общая площадь, кв. м'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='villa_photos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.villaphotos', verbose_name='Фотография виллы'),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='yacht_photos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.yachtphotos', verbose_name='Фотография яхты'),
        ),
    ]
