# Generated by Django 4.2 on 2023-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0007_villa_photo1_villa_photo2_villa_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
