# Generated by Django 4.2 on 2023-04-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0009_vehicle_photo1_vehicle_photo2_yacht_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='villa_photos',
        ),
        migrations.DeleteModel(
            name='VillaPhotos',
        ),
    ]
