# Generated by Django 4.2 on 2023-04-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0010_remove_villa_villa_photos_delete_villaphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 2')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 3')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 4')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 5')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 6')),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 7')),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 8')),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 9')),
                ('photo_10', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото 10')),
                ('villa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation.villa', verbose_name='Вилла')),
            ],
            options={
                'verbose_name': 'Фотография виллы',
                'verbose_name_plural': 'Фотографии виллы',
            },
        ),
    ]
