# Generated by Django 4.2 on 2023-05-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0012_remove_vehicle_vehicle_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='villa',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='yacht',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterIndexTogether(
            name='villa',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='yacht',
            index_together={('id', 'slug')},
        ),
        migrations.AddField(
            model_name='villa',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_villa', to='vacation.category'),
        ),
        migrations.AddField(
            model_name='yacht',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_yacht', to='vacation.category'),
        ),
    ]
