# Generated by Django 4.2 on 2023-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0013_category_villa_slug_yacht_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='slug',
            field=models.SlugField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='slug',
            field=models.SlugField(default=False, max_length=200),
        ),
    ]
