# Generated by Django 4.2 on 2023-05-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0014_alter_villa_slug_alter_yacht_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Катеририя', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='villaphotos',
            options={'verbose_name': 'Фотография виллы', 'verbose_name_plural': 'Фотографии вилл'},
        ),
        migrations.AlterModelOptions(
            name='yachtphotos',
            options={'verbose_name': 'Фотография яхты', 'verbose_name_plural': 'Фотографии яхт'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='photo5',
        ),
    ]
