# Generated by Django 4.2 on 2023-05-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0015_alter_category_options_alter_villaphotos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='category',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
