# Generated by Django 5.2.1 on 2025-05-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0016_remove_villa_category_remove_yacht_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photos', to='vacation.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фотографии автомобиля',
            },
        ),
        migrations.CreateModel(
            name='VillaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('villa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villa_photos', to='vacation.villa', verbose_name='Вилла')),
            ],
            options={
                'verbose_name': 'Фото виллы',
                'verbose_name_plural': 'Фотографии виллы',
            },
        ),
        migrations.CreateModel(
            name='YachtPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yacht', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yacht_photos', to='vacation.yacht', verbose_name='Яхта')),
            ],
            options={
                'verbose_name': 'Фото яхты',
                'verbose_name_plural': 'Фотографии яхты',
            },
        ),
    ]
