# Generated by Django 5.2.1 on 2025-05-28 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0017_vehiclephoto_villaphoto_yachtphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephoto',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_photos', to='vacation.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='villaphoto',
            name='villa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villa_photos', to='vacation.villa', verbose_name='Вилла'),
        ),
        migrations.AlterField(
            model_name='yachtphoto',
            name='yacht',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yacht_photos', to='vacation.yacht', verbose_name='Яхта'),
        ),
    ]
