# Generated by Django 5.2.1 on 2025-05-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0018_alter_vehiclephoto_vehicle_alter_villaphoto_villa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villaphotos',
            name='villa',
        ),
        migrations.RemoveField(
            model_name='yachtphotos',
            name='yacht',
        ),
        migrations.DeleteModel(
            name='VehiclePhotos',
        ),
        migrations.DeleteModel(
            name='VillaPhotos',
        ),
        migrations.DeleteModel(
            name='YachtPhotos',
        ),
    ]
